services:
    db:
        build:
            context: ./postgres
        container_name: ratatosk-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - ratatosk_db_data:/var/lib/postgresql/data
    test-db:
        build:
            context: ./postgres
        container_name: ratatosk-testdb
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: "${TEST_POSTGRES_DB}"
            POSTGRES_USER: "${TEST_POSTGRES_USER}"
            POSTGRES_PASSWORD: "${TEST_POSTGRES_PASSWORD}"
        volumes:
            - ratatosk_testdb_data:/var/lib/postgresql/data

volumes:
    ratatosk_db_data:
    ratatosk_testdb_data:
