services:
    db:
        build:
            context: ./postgres
        container_name: ratatosk-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - ratatosk_db_data:/var/lib/postgresql/data
    api:
        build:
            context: .
        container_name: ratatosk-api
        ports:
            - "5000:8080"
        depends_on:
            - db
        environment:
            Authentication__Secret: "${AUTHENTICATION_SECRET}"
            Database__ConnectionString: "Host=ratatosk-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
            Eventstore__Type: 2

volumes:
    ratatosk_db_data:
