services:
  ratatosk-testdb:
    build:
      context: ./postgres
    container_name: ratatosk-testdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${TEST_POSTGRES_DB}"
      POSTGRES_USER: "${TEST_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${TEST_POSTGRES_PASSWORD}"
    volumes:
      - ratatosk_testdb_data:/var/lib/postgresql/data

  ratatosk-api-ci:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ratatosk-api:ci
    profiles: [ "ci" ]
    depends_on:
      - ratatosk-testdb
    ports:
      - "5000:8080"
    environment:
      # Connection string using service name for hostname
      Database__ConnectionString: "Host=ratatosk-testdb;Port=5432;Database=${TEST_POSTGRES_DB};Username=${TEST_POSTGRES_USER};Password=${TEST_POSTGRES_PASSWORD}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 5

  # Image built locally (only used locally)
  ratatosk-api-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratatosk-api-local
    profiles: [ "local" ]
    depends_on:
      - ratatosk-testdb
    ports:
      - "5005:8080"
    environment:
      Database__ConnectionString: "Host=ratatosk-testdb;Port=5432;Database=${TEST_POSTGRES_DB};Username=${TEST_POSTGRES_USER};Password=${TEST_POSTGRES_PASSWORD}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://ratatosk-api-local:8080/healthz" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  ratatosk_testdb_data:
