name: "Set Image Metadata"
description: "Sets lowercase IMAGE_NAME and IMAGE_TAG env vars"
inputs:
  image-tag:
    description: "The tag of the image to build"
    required: false
    default: "ci"
runs:
  using: "composite"
  steps:
    - run: |
        echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}/ratatosk-api" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ inputs.image-tag }}" >> $GITHUB_ENV
      shell: bash